### ISSUE TITLE
Feature request: Add 'Try with colab' option near code snippets

### ISSUE THREAD

**Issue by btkcodedev** [airbytehq/airbyte-lib-private-beta#23]
Feature Request:
Add 'Try with colab' option **near** the code snippets in the docs for easier access
![image](https://github.com/airbytehq/airbyte-lib-private-beta/assets/47392334/a7ec0473-b521-4348-a7ca-55e699f4ca8e)

This feature will be helpful for all Google colab users

**Comment by aaronsteers** [comment]
Great idea - thanks, @btkcodedev !

**Comment by aaronsteers** [comment]
@btkcodedev - I created a quick one-liner which adds this:

- #https://github.com/airbytehq/airbyte/pull/35215

Will merge shortly.

**Comment by aaronsteers** [comment]
Done ✅ 

Thanks again @btkcodedev for this suggestion. 🙏
